mobile_phones-master/MobilePhones/Areas/Admin/Controllers/FileController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using MobilePhones.Models;
using MobilePhones.ViewModels;

namespace MobilePhones.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize]
    public class FileController : Controller
    {
        private readonly MobileContext _context;
        private readonly UserManager<User> _userManager;

        public FileController(UserManager<User> userManager, MobileContext context)
        {
            _userManager = userManager;
            _context = context;
        }
        public async Task<IActionResult> Index()
        {
            var fileuploadViewModel = await LoadAllFiles();
            return View(fileuploadViewModel);
        }

        private async Task<FileUploadViewModel> LoadAllFiles()
        {
            var viewModel = new FileUploadViewModel();
            viewModel.FilesOnDatabase = await _context.FilesOnDatabase.Include("User").ToListAsync();
            viewModel.FilesOnFileSystem = await _context.FilesOnFileSystem.Include("User").ToListAsync();
            return viewModel;
        }

        [HttpPost]
        public async Task<IActionResult> UploadToFileSystem(List<IFormFile> files, string description)
        {
            foreach (var file in files)
            {
                var basePath = Path.Combine(Directory.GetCurrentDirectory() + "\\Files\\");
                bool basePathExists = System.IO.Directory.Exists(basePath);
                if (!basePathExists) 
                {
                    Directory.CreateDirectory(basePath);
                }
                var fileName = Path.GetFileNameWithoutExtension(file.FileName);
                var filePath = Path.Combine(basePath, file.FileName);
                var extension = Path.GetExtension(file.FileName);
                if (!System.IO.File.Exists(filePath))
                {
                    using (var stream = new FileStream(filePath, FileMode.Create))
                    {
                        await file.CopyToAsync(stream);
                    }
                    var fileModel = new FileOnFileSystemModel
                    {
                        CreatedOn = DateTime.UtcNow,
                        FileType = file.ContentType,
                        Extension = extension,
                        Name = fileName,
                        Description = description,
                        FilePath = filePath,
                        UserId = _userManager.GetUserId(User)
                    };
                    _context.FilesOnFileSystem.Add(fileModel);
                    _context.SaveChanges();
                }
            }
            TempData["success"] = "Файл успешно загружен в систему";
            return RedirectToAction("Index");
        }

        public async Task<IActionResult> DownloadFileFromFileSystem(int id)
        {
            var file = await _context.FilesOnFileSystem.Where(x => x.Id == id).FirstOrDefaultAsync();
            if (file == null) return null;
            var memory = new MemoryStream();
            using (var stream = new FileStream(file.FilePath, FileMode.Open))
            {
                await stream.CopyToAsync(memory);
            }
            memory.Position = 0;
            return File(memory, file.FileType, file.Name + file.Extension);
        }

        public async Task<IActionResult> DeleteFileFromFileSystem(int id)
        {
            var file = await _context.FilesOnFileSystem.Where(x => x.Id == id).FirstOrDefaultAsync();
            if (file == null) return null;
            if (System.IO.File.Exists(file.FilePath))
            {
                System.IO.File.Delete(file.FilePath);
            }
            _context.FilesOnFileSystem.Remove(file);
            _context.SaveChanges();
            TempData["warning"] = $"Файл {file.Name + file.Extension} успешно удален из системы.";
            return RedirectToAction("Index");
        }

        [HttpPost]

        public async Task<IActionResult> UploadToDatabase(List<IFormFile> files, string description)
        {
            foreach (var file in files)
            {
                var fileName = Path.GetFileNameWithoutExtension(file.FileName);
                var extension = Path.GetExtension(file.FileName);
                var fileModel = new FileOnDatabaseModel
                {
                    CreatedOn = DateTime.UtcNow,
                    FileType = file.ContentType,
                    Extension = extension,
                    Name = fileName,
                    Description = description,
                    UserId = _userManager.GetUserId(User)
                };
                using (var dataStream = new MemoryStream())
                {
                    await file.CopyToAsync(dataStream);
                    fileModel.Data = dataStream.ToArray();
                }
                _context.FilesOnDatabase.Add(fileModel);
                _context.SaveChanges();
            }
            TempData["success"] = "Файл успешно сохранен в базу данных";
            return RedirectToAction("Index");
        }

        public async Task<IActionResult> DownloadFileFromDatabase(int id)
        {
            var file = await _context.FilesOnDatabase.Where(x => x.Id == id).FirstOrDefaultAsync();
            if (file == null) return null;
            return File(file.Data, file.FileType, file.Name + file.Extension);
        }

        public async Task<IActionResult> DeleteFileFromDatabase(int id)
        {
            var file = await _context.FilesOnDatabase.Where(x => x.Id == id).FirstOrDefaultAsync();
            _context.FilesOnDatabase.Remove(file);
            _context.SaveChanges();
            TempData["warning"] = $"Файл {file.Name + file.Extension} успешно удален из базы данных.";
            return RedirectToAction("Index");
        }
    }
}

mobile_phones-master/MobilePhones/Controllers/PhonesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using MobilePhones.Models;

namespace MobilePhones.Controllers
{
    public class PhonesController : Controller
    {
        private readonly MobileContext _context;

        public PhonesController(MobileContext context)
        {
            _context = context;
        }

        // GET: Phones
        public async Task<IActionResult> Index()
        {
            return View(await _context.Phones.ToListAsync());
        }

        // GET: Phones/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var phone = await _context.Phones
                .FirstOrDefaultAsync(m => m.Id == id);
            if (phone == null)
            {
                return NotFound();
            }

            return View(phone);
        }

        [HttpPost]
        public IActionResult Order(int phone_id, string user, string address, string phone)
        {
            var result = new object();
            if (phone_id != 0 && phone != null)
            {
                Order order = new Order() { 
                    PhoneId = phone_id, 
                    User = user, 
                    Address = address, 
                    ContactPhone = phone,
                    DateTime = DateTime.Now
                };
                _context.Add(order);
                _context.SaveChanges();
                result = new { message = "success" };
            } else
            {
                result = new { message = "error" };
            }

            return Ok(result);
        }


        private bool PhoneExists(int id)
        {
            return _context.Phones.Any(e => e.Id == id);
        }
    }
}

mobile_phones-master/MobilePhones/Areas/Admin/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Admin Panel</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/lib/fontawesome/css/all.min.css" />
    <link rel="stylesheet" href="~/lib/select2/css/select2.min.css"  />
    <link rel="stylesheet" href="~/lib/select2-bootstrap4/css/select2-bootstrap4.min.css"  />
    <link rel="stylesheet" href="~/lib/charts/chart.min.css"  />
    <link rel="stylesheet" href="~/css/site.css" />

</head>
<body>
    <nav class="navbar navbar-dark sticky-top bg-dark flex-md-nowrap p-0 shadow">
        <a class="navbar-brand col-md-3 col-lg-2 mr-0 px-3" href="#">Mobile Phone</a>
        <button class="navbar-toggler position-absolute d-md-none collapsed" type="button" data-toggle="collapse" data-target="#sidebarMenu" aria-controls="sidebarMenu" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <form action="/Admin/Phones" method="get" class="w-100">
            <input name="search" class="form-control form-control-dark w-100"
                   type="text" placeholder="Search Phones" aria-label="Search">
        </form>
        <ul class="navbar-nav px-3">
            <li class="nav-item text-nowrap">
                <a class="nav-link" href="#">Sign out</a>
            </li>
        </ul>
    </nav>
    <div class="container-fluid">

        <div class="row">
            <nav id="sidebarMenu" class="col-md-3 col-lg-2 d-md-block bg-light sidebar collapse">
                <div class="sidebar-sticky pt-3">
                    <ul class="nav flex-column">
                        <li class="nav-item">
                            <a class="nav-link active" asp-area="Admin" asp-controller="Home" asp-action="Index">
                                <i class="fas fa-home"></i>
                                Dashboard <span class="sr-only">(current)</span>
                            </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" asp-area="Admin" asp-controller="Phones" asp-action="Index">
                                <i class="fas fa-mobile-alt"></i>
                                Phones
                            </a>
                        </li>

                        <li class="nav-item">
                            <a class="nav-link" asp-area="Admin" asp-controller="Orders" asp-action="Index">
                                <i class="fas fa-file-alt"></i>
                                Orders
                            </a>
                        </li>

                        <li class="nav-item">
                            <a class="nav-link" asp-area="Admin" asp-controller="File" asp-action="Index">
                                <i class="fas fa-archive"></i>
                                Files
                            </a>
                        </li>


                        @if (User.IsInRole("admin"))
                        {
                            <li class="nav-item">
                                <a class="nav-link" asp-area="Admin" asp-controller="Role" asp-action="Index">
                                    <i class="fas fa-user-cog"></i>
                                    Roles
                                </a>
                            </li>
                        }

                    </ul>

                    <ul class="nav flex-column mb-2">
                        <li class="nav-item">
                            <a class="nav-link" href="/">
                                <span data-feather="file-text"></span>
                                Client side root page
                            </a>
                        </li>

                    </ul>

                    <h6 class="sidebar-heading d-flex justify-content-between align-items-center px-3 mt-4 mb-1 text-muted">
                        <span>Saved reports</span>
                        <a class="d-flex align-items-center text-muted" href="#" aria-label="Add a new report">
                            <span data-feather="plus-circle"></span>
                        </a>
                    </h6>
                    <ul class="nav flex-column mb-2">
                        <li class="nav-item">
                            <a class="nav-link" href="#">
                                <span data-feather="file-text"></span>
                                Current month
                            </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="#">
                                <span data-feather="file-text"></span>
                                Last quarter
                            </a>
                        </li>

                    </ul>
                </div>
            </nav>
            <main role="main" class="col-md-9 ml-sm-auto col-lg-10">
                @if (TempData.ContainsKey("danger"))
                {
                    <div class="alert alert-danger alert-dismissible fade show" role="alert">
                        @TempData["danger"]
                        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                    </div>
                }
                @if (TempData.ContainsKey("success"))
                {
                    <div class="alert alert-success alert-dismissible fade show" role="alert">
                        @TempData["success"]
                        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                    </div>
                }
                @if (TempData.ContainsKey("warning"))
                {
                    <div class="alert alert-warning alert-dismissible fade show" role="alert">
                        @TempData["warning"]
                        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                    </div>
                }
                @if (TempData.ContainsKey("primary"))
                {
                    <div class="alert alert-primary alert-dismissible fade show" role="alert">
                        @TempData["primary"]
                        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                    </div>
                }
                @RenderBody()
            </main>
        </div>

    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - MobilePhones - <a asp-area="Admin" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/lib/fontawesome/js/all.min.js"></script>
    <script src="https://unpkg.com/feather-icons/dist/feather.min.js"></script>
    <script src="~/js/custom.js" asp-append-version="true"></script>
    <script src="~/lib/select2/js/select2.full.min.js"></script>
    <script src="~/lib/select2/js/i18n/ru.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="~/js/select2.js"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>